/*
 * Domino.java
 *
 * Created on 27 de agosto de 2006, 18:32
 */
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package dominoprolog;
import org.jpl7.*;
/**
 *
 * Jorge Robla y Fernando Seguino
 */
public class DominoProlog extends javax.swing.JFrame {

    String t1 = "consult('domino.pl')";

    
    public DominoProlog() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        Consulta = new javax.swing.JTextField();
        Respuesta = new javax.swing.JTextField();
        LabelConsulta = new javax.swing.JLabel();
        LabelRespuesta = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Domino");
        setResizable(false);
        Consulta.setFont(new java.awt.Font("Arial", 0, 14));

        Respuesta.setFont(new java.awt.Font("Arial", 0, 14));

        LabelConsulta.setText("Ingrese las piezas");

        LabelRespuesta.setText("Soluci\u00f3n");

        jButton1.setText("Responder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(LabelConsulta)
                            .add(LabelRespuesta))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Respuesta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 336, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Consulta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 336, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(66, 66, 66)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(Consulta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(LabelConsulta))
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(jButton1)
                        .add(30, 30, 30)
                        .add(LabelRespuesta))
                    .add(Respuesta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        consultar();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public String traducir(String rpta){
   
        int cant = 0, pares = 0;
        char ch;
        String lista = new String("[");        
        boolean control = false;
        while (cant < rpta.length()){
            ch = rpta.charAt(cant);            
            
            if (java.lang.Character.isDigit(ch)){
                if (pares == 0){
                    pares++;
                    if (! control) {                                                
                        lista = lista + "[" + ch + ",";
                        control = true;
                    }
                    else 
                        lista = lista + ",[" + ch + ",";
                }
                else{
                    pares = 0;
                    lista = lista + ch + "]";
                }
            }
            cant++;
        }
        
        lista = lista + "]";    
        return(lista);
    }
    
    public boolean verificarCorchetes(String cadena){
        int cont = 0;
        int corchetes = 0;
                
        while (cont < cadena.length()){
            
            char ch = cadena.charAt(cont);
            
            if (ch == '[')
                corchetes++;            
            else if (ch == ']')
                corchetes--;
                
            cont++;
        }
        
        return (corchetes == 0);        
    }
    
    
    public void consultar(){

        String consulta = Consulta.getText();
        
        
        
        if (verificarCorchetes(consulta)){
            Query q1 = new Query(t1);
            q1.hasSolution();
            String t2 = "domino(" + consulta + ",Rpta)";
            Query q2 = new Query(t2);

            if (q2.hasSolution()){
                String rpta = q2.oneSolution().get("Rpta").toString();
                String rptaTradu = traducir(rpta);
                Respuesta.setText(rptaTradu);
            }
            else
                Respuesta.setText("No tiene solución.");            
        }
        else
            Respuesta.setText("Verifique los cochetes.");            
    }
    
   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DominoProlog().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Consulta;
    private javax.swing.JLabel LabelConsulta;
    private javax.swing.JLabel LabelRespuesta;
    private javax.swing.JTextField Respuesta;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    
}

